// Code generated by gola 0.2.1; DO NOT EDIT.

package song_user_favourites

const insertWithoutPK string = "INSERT IGNORE INTO `song_user_favourites` (`user_id`, `song_id`, `remark`, `is_favourite`, `created_at`, `updated_at`) values (?, ?, ?, ?, ?, ?)"
