// Code generated by gola 0.1.1; DO NOT EDIT.

package myusers

import (
	"fmt"
	"strings"

	"github.com/olachat/gola/coredb"
)

type orderBy int

type idxQuery[T any] struct {
	whereSql    string
	limitSql    string
	orders      []string
	whereParams []any
}

// order by enum & interface
const (
	IdAsc orderBy = iota
	IdDesc
	NameAsc
	NameDesc
	BalanceAsc
	BalanceDesc
	AgeAsc
	AgeDesc
	DataAsc
	DataDesc
	CreateDtAsc
	CreateDtDesc
)

func (q *idxQuery[T]) OrderBy(args ...orderBy) coredb.ReadQuery[T] {
	q.orders = make([]string, len(args))
	for i, arg := range args {
		switch arg {
		case IdAsc:
			q.orders[i] = "`id` asc"
		case IdDesc:
			q.orders[i] = "`id` desc"
		case NameAsc:
			q.orders[i] = "`name` asc"
		case NameDesc:
			q.orders[i] = "`name` desc"
		case BalanceAsc:
			q.orders[i] = "`balance` asc"
		case BalanceDesc:
			q.orders[i] = "`balance` desc"
		case AgeAsc:
			q.orders[i] = "`age` asc"
		case AgeDesc:
			q.orders[i] = "`age` desc"
		case DataAsc:
			q.orders[i] = "`data` asc"
		case DataDesc:
			q.orders[i] = "`data` desc"
		case CreateDtAsc:
			q.orders[i] = "`create_dt` asc"
		case CreateDtDesc:
			q.orders[i] = "`create_dt` desc"
		}
	}
	return q
}

func (q *idxQuery[T]) All() []*T {
	result, _ := coredb.Find[T](DBName, TableName, q)
	return result
}

func (q *idxQuery[T]) Limit(offset, limit int) []*T {
	q.limitSql = fmt.Sprintf(" limit %d, %d", offset, limit)
	result, _ := coredb.Find[T](DBName, TableName, q)
	return result
}

type order[T any] interface {
	OrderBy(args ...orderBy) coredb.ReadQuery[T]
}

type orderReadQuery[T any] interface {
	order[T]
	coredb.ReadQuery[T]
}

type iQuery[T any] interface {
	WhereAgeEQ(val int) orderReadQuery[T]
	WhereAgeIN(vals ...int) orderReadQuery[T]
	orderReadQuery[T]
}

// Find methods

// Select returns rows from `myusers` table with index awared query
func Select() iQuery[Myuser] {
	return new(idxQuery[Myuser])
}

// SelectFields returns rows with selected fields from `myusers` table with index awared query
func SelectFields[T any]() iQuery[T] {
	return new(idxQuery[T])
}

func (q *idxQuery[T]) WhereAgeEQ(val int) orderReadQuery[T] {
	q.whereSql += " where `age` = ?"
	q.whereParams = append(q.whereParams, val)
	return q
}

func (q *idxQuery[T]) WhereAgeIN(vals ...int) orderReadQuery[T] {
	q.whereSql = " where `age` in (" + coredb.GetParamPlaceHolder(len(vals)) + ")"
	for _, val := range vals {
		q.whereParams = append(q.whereParams, val)
	}
	return q
}

func (q *idxQuery[T]) GetWhere() (whereSql string, params []any) {
	var orderSql string
	if len(q.orders) > 0 {
		orderSql = " order by " + strings.Join(q.orders, ",")
	}
	return q.whereSql + orderSql + q.limitSql, q.whereParams
}
