// Code generated by gola 0.1.1; DO NOT EDIT.

package myusers

import (
	"database/sql"
	"encoding/json"
	"reflect"
	"strings"

	"github.com/olachat/gola/coredb"

	"github.com/volatiletech/null/v8"
)

const DBName string = "memory"
const TableName string = "myusers"

// Myuser represents `myusers` table
type Myuser struct {
	//  INTEGER
	Id `json:"id"`
	//  TEXT
	Name `json:"name"`
	//  REAL
	Balance `json:"balance"`
	//  INTEGER
	Age `json:"age"`
	//  BLOB
	Data `json:"data"`
	//  NUMERIC
	CreateDt `json:"create_dt"`
}

type withPK interface {
	GetId() int
}

// FetchByPK returns a row from `myusers` table with given primary key value
func FetchByPK(val int) *Myuser {
	return coredb.FetchByPK[Myuser](DBName, TableName, []string{"id"}, val)
}

// FetchFieldsByPK returns a row with selected fields from myusers table with given primary key value
func FetchFieldsByPK[T any](val int) *T {
	return coredb.FetchByPK[T](DBName, TableName, []string{"id"}, val)
}

// FetchByPKs returns rows with from `myusers` table with given primary key values
func FetchByPKs(vals ...int) []*Myuser {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKs[Myuser](DBName, TableName, "id", pks)
}

// FetchFieldsByPKs returns rows with selected fields from `myusers` table with given primary key values
func FetchFieldsByPKs[T any](vals ...int) []*T {
	pks := coredb.GetAnySlice(vals)
	return coredb.FetchByPKs[T](DBName, TableName, "id", pks)
}

// FindOne returns a row from `myusers` table with arbitary where query
// whereSQL must start with "where ..."
func FindOne(whereSQL string, params ...any) *Myuser {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOne[Myuser](DBName, TableName, w)
}

// FindOneFields returns a row with selected fields from `myusers` table with arbitary where query
// whereSQL must start with "where ..."
func FindOneFields[T any](whereSQL string, params ...any) *T {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.FindOne[T](DBName, TableName, w)
}

// Find returns rows from `myusers` table with arbitary where query
// whereSQL must start with "where ..."
func Find(whereSQL string, params ...any) ([]*Myuser, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.Find[Myuser](DBName, TableName, w)
}

// FindFields returns rows with selected fields from `myusers` table with arbitary where query
// whereSQL must start with "where ..."
func FindFields[T any](whereSQL string, params ...any) ([]*T, error) {
	w := coredb.NewWhere(whereSQL, params...)
	return coredb.Find[T](DBName, TableName, w)
}

// Count returns select count(*) with arbitary where query
// whereSQL must start with "where ..."
func Count(whereSQL string, params ...any) (int, error) {
	return coredb.QueryInt(DBName, "SELECT COUNT(*) FROM `myusers` "+whereSQL, params...)
}

// Column types

// Id field
type Id struct {
	isAssigned bool
	val        int
}

func (c *Id) GetId() int {
	return c.val
}

func (c *Id) GetColumnName() string {
	return "id"
}

func (c *Id) GetValPointer() any {
	return &c.val
}

func (c *Id) MarshalJSON() ([]byte, error) {
	return json.Marshal(&c.val)
}

func (c *Id) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &c.val); err != nil {
		return err
	}

	return nil
}

// Name field
type Name struct {
	_updated bool
	val      null.String
}

func (c *Name) GetName() null.String {
	return c.val
}

func (c *Name) SetName(val null.String) bool {
	c._updated = true
	c.val = val
	return true
}

func (c *Name) IsUpdated() bool {
	return c._updated
}

func (c *Name) resetUpdated() {
	c._updated = false
}

func (c *Name) GetColumnName() string {
	return "name"
}

func (c *Name) GetValPointer() any {
	return &c.val
}

func (c *Name) MarshalJSON() ([]byte, error) {
	return json.Marshal(&c.val)
}

func (c *Name) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &c.val); err != nil {
		return err
	}

	return nil
}

// Balance field
type Balance struct {
	_updated bool
	val      null.Float32
}

func (c *Balance) GetBalance() null.Float32 {
	return c.val
}

func (c *Balance) SetBalance(val null.Float32) bool {
	c._updated = true
	c.val = val
	return true
}

func (c *Balance) IsUpdated() bool {
	return c._updated
}

func (c *Balance) resetUpdated() {
	c._updated = false
}

func (c *Balance) GetColumnName() string {
	return "balance"
}

func (c *Balance) GetValPointer() any {
	return &c.val
}

func (c *Balance) MarshalJSON() ([]byte, error) {
	return json.Marshal(&c.val)
}

func (c *Balance) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &c.val); err != nil {
		return err
	}

	return nil
}

// Age field
type Age struct {
	_updated bool
	val      null.Int
}

func (c *Age) GetAge() null.Int {
	return c.val
}

func (c *Age) SetAge(val null.Int) bool {
	c._updated = true
	c.val = val
	return true
}

func (c *Age) IsUpdated() bool {
	return c._updated
}

func (c *Age) resetUpdated() {
	c._updated = false
}

func (c *Age) GetColumnName() string {
	return "age"
}

func (c *Age) GetValPointer() any {
	return &c.val
}

func (c *Age) MarshalJSON() ([]byte, error) {
	return json.Marshal(&c.val)
}

func (c *Age) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &c.val); err != nil {
		return err
	}

	return nil
}

// Data field
type Data struct {
	_updated bool
	val      null.Bytes
}

func (c *Data) GetData() null.Bytes {
	return c.val
}

func (c *Data) SetData(val null.Bytes) bool {
	c._updated = true
	c.val = val
	return true
}

func (c *Data) IsUpdated() bool {
	return c._updated
}

func (c *Data) resetUpdated() {
	c._updated = false
}

func (c *Data) GetColumnName() string {
	return "data"
}

func (c *Data) GetValPointer() any {
	return &c.val
}

func (c *Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(&c.val)
}

func (c *Data) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &c.val); err != nil {
		return err
	}

	return nil
}

// CreateDt field
type CreateDt struct {
	_updated bool
	val      null.Float32
}

func (c *CreateDt) GetCreateDt() null.Float32 {
	return c.val
}

func (c *CreateDt) SetCreateDt(val null.Float32) bool {
	c._updated = true
	c.val = val
	return true
}

func (c *CreateDt) IsUpdated() bool {
	return c._updated
}

func (c *CreateDt) resetUpdated() {
	c._updated = false
}

func (c *CreateDt) GetColumnName() string {
	return "create_dt"
}

func (c *CreateDt) GetValPointer() any {
	return &c.val
}

func (c *CreateDt) MarshalJSON() ([]byte, error) {
	return json.Marshal(&c.val)
}

func (c *CreateDt) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &c.val); err != nil {
		return err
	}

	return nil
}

// New return new *Myuser with default values
func New() *Myuser {
	return &Myuser{
		Id{},
		Name{val: null.StringFromPtr(nil)},
		Balance{val: null.Float32FromPtr(nil)},
		Age{val: null.IntFromPtr(nil)},
		Data{val: null.BytesFromPtr(nil)},
		CreateDt{val: null.Float32FromPtr(nil)},
	}
}

// NewWithPK takes "id"
// and returns new *Myuser with given PK
func NewWithPK(val int) *Myuser {
	c := &Myuser{
		Id{},
		Name{val: null.StringFromPtr(nil)},
		Balance{val: null.Float32FromPtr(nil)},
		Age{val: null.IntFromPtr(nil)},
		Data{val: null.BytesFromPtr(nil)},
		CreateDt{val: null.Float32FromPtr(nil)},
	}
	c.Id.val = val
	c.Id.isAssigned = true
	return c
}

const insertWithoutPK string = "INSERT IGNORE INTO `myusers` (`name`, `balance`, `age`, `data`, `create_dt`) values (?, ?, ?, ?, ?)"
const insertWithPK string = "INSERT IGNORE INTO `myusers` (`id`, `name`, `balance`, `age`, `data`, `create_dt`) values (?, ?, ?, ?, ?, ?)"

// Insert Myuser struct to `myusers` table
func (c *Myuser) Insert() error {
	var result sql.Result
	var err error
	if c.Id.isAssigned {
		result, err = coredb.Exec(DBName, insertWithPK, c.GetId(), c.GetName(), c.GetBalance(), c.GetAge(), c.GetData(), c.GetCreateDt())
		if err != nil {
			return err
		}
	} else {
		result, err = coredb.Exec(DBName, insertWithoutPK, c.GetName(), c.GetBalance(), c.GetAge(), c.GetData(), c.GetCreateDt())
		if err != nil {
			return err
		}

		id, err := result.LastInsertId()
		if err != nil {
			return err
		}
		c.Id.val = int(id)
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if affectedRows == 0 {
		return coredb.ErrAvoidInsert
	}

	c.resetUpdated()
	return nil
}

func (c *Myuser) resetUpdated() {
	c.Name.resetUpdated()
	c.Balance.resetUpdated()
	c.Age.resetUpdated()
	c.Data.resetUpdated()
	c.CreateDt.resetUpdated()
}

// Update Myuser struct in `myusers` table
func (obj *Myuser) Update() (bool, error) {
	var updatedFields []string
	var params []any
	if obj.Name.IsUpdated() {
		updatedFields = append(updatedFields, "`name` = ?")
		params = append(params, obj.GetName())
	}
	if obj.Balance.IsUpdated() {
		updatedFields = append(updatedFields, "`balance` = ?")
		params = append(params, obj.GetBalance())
	}
	if obj.Age.IsUpdated() {
		updatedFields = append(updatedFields, "`age` = ?")
		params = append(params, obj.GetAge())
	}
	if obj.Data.IsUpdated() {
		updatedFields = append(updatedFields, "`data` = ?")
		params = append(params, obj.GetData())
	}
	if obj.CreateDt.IsUpdated() {
		updatedFields = append(updatedFields, "`create_dt` = ?")
		params = append(params, obj.GetCreateDt())
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `myusers` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `id` = ?"
	params = append(params, obj.GetId())

	result, err := coredb.Exec(DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	obj.resetUpdated()
	return true, nil
}

// Update Myuser struct with given fields in `myusers` table
func Update(obj withPK) (bool, error) {
	var updatedFields []string
	var params []any
	var resetFuncs []func()

	val := reflect.ValueOf(obj).Elem()
	updatedFields = make([]string, 0, val.NumField())
	params = make([]any, 0, val.NumField())

	for i := 0; i < val.NumField(); i++ {
		col := val.Field(i).Addr().Interface()

		switch c := col.(type) {
		case *Name:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`name` = ?")
				params = append(params, c.GetName())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Balance:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`balance` = ?")
				params = append(params, c.GetBalance())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Age:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`age` = ?")
				params = append(params, c.GetAge())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *Data:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`data` = ?")
				params = append(params, c.GetData())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		case *CreateDt:
			if c.IsUpdated() {
				updatedFields = append(updatedFields, "`create_dt` = ?")
				params = append(params, c.GetCreateDt())
				resetFuncs = append(resetFuncs, c.resetUpdated)
			}
		}
	}

	if len(updatedFields) == 0 {
		return false, nil
	}

	sql := "UPDATE `myusers` SET "
	sql = sql + strings.Join(updatedFields, ",") + " WHERE `id` = ?"
	params = append(params, obj.GetId())

	result, err := coredb.Exec(DBName, sql, params...)
	if err != nil {
		return false, err
	}

	affectedRows, err := result.RowsAffected()
	if err != nil {
		return false, err
	}
	if affectedRows == 0 {
		return false, coredb.ErrAvoidUpdate
	}

	for _, f := range resetFuncs {
		f()
	}
	return true, nil
}

const deleteSql string = "DELETE FROM `myusers` WHERE `id` = ?"

// DeleteByPK delete a row from myusers table with given primary key value
func DeleteByPK(val int) error {
	_, err := coredb.Exec(DBName, deleteSql, val)
	return err
}
