// Code generated by gola 0.1.1; DO NOT EDIT.

package myusers

const insertWithoutPK string = "INSERT INTO `myusers` (`name`, `balance`, `age`, `data`, `create_dt`) values (?, ?, ?, ?, ?)"
const insertWithPK string = "INSERT INTO `myusers` (`id`, `name`, `balance`, `age`, `data`, `create_dt`) values (?, ?, ?, ?, ?, ?)"
