// Code generated by gola 0.2.1; DO NOT EDIT.

package type_monsters

import (
	"fmt"
	"strings"

	"github.com/olachat/gola/coredb"
)

type orderBy int

type idxQuery[T any] struct {
	whereSql    string
	limitSql    string
	orders      []string
	whereParams []any
}

// order by enum & interface
const (
	IdAsc orderBy = iota
	IdDesc
	IdTwoAsc
	IdTwoDesc
	IdThreeAsc
	IdThreeDesc
	BoolZeroAsc
	BoolZeroDesc
	BoolOneAsc
	BoolOneDesc
	BoolTwoAsc
	BoolTwoDesc
	BoolThreeAsc
	BoolThreeDesc
	BoolFourAsc
	BoolFourDesc
	BoolFiveAsc
	BoolFiveDesc
	BoolSixAsc
	BoolSixDesc
	StringZeroAsc
	StringZeroDesc
	StringOneAsc
	StringOneDesc
	StringTwoAsc
	StringTwoDesc
	StringThreeAsc
	StringThreeDesc
	StringFourAsc
	StringFourDesc
	StringFiveAsc
	StringFiveDesc
	StringSixAsc
	StringSixDesc
	StringSevenAsc
	StringSevenDesc
	StringEightAsc
	StringEightDesc
	StringNineAsc
	StringNineDesc
	StringTenAsc
	StringTenDesc
	StringElevenAsc
	StringElevenDesc
	BigIntZeroAsc
	BigIntZeroDesc
	BigIntOneAsc
	BigIntOneDesc
	BigIntTwoAsc
	BigIntTwoDesc
	BigIntThreeAsc
	BigIntThreeDesc
	BigIntFourAsc
	BigIntFourDesc
	BigIntFiveAsc
	BigIntFiveDesc
	BigIntSixAsc
	BigIntSixDesc
	IntZeroAsc
	IntZeroDesc
	IntOneAsc
	IntOneDesc
	IntTwoAsc
	IntTwoDesc
	IntThreeAsc
	IntThreeDesc
	IntFourAsc
	IntFourDesc
	IntFiveAsc
	IntFiveDesc
	IntSixAsc
	IntSixDesc
	FloatZeroAsc
	FloatZeroDesc
	FloatOneAsc
	FloatOneDesc
	FloatTwoAsc
	FloatTwoDesc
	FloatThreeAsc
	FloatThreeDesc
	FloatFourAsc
	FloatFourDesc
	FloatFiveAsc
	FloatFiveDesc
	FloatSixAsc
	FloatSixDesc
	FloatSevenAsc
	FloatSevenDesc
	FloatEightAsc
	FloatEightDesc
	FloatNineAsc
	FloatNineDesc
	ByteaZeroAsc
	ByteaZeroDesc
	ByteaOneAsc
	ByteaOneDesc
	ByteaTwoAsc
	ByteaTwoDesc
	ByteaThreeAsc
	ByteaThreeDesc
	ByteaFourAsc
	ByteaFourDesc
	ByteaFiveAsc
	ByteaFiveDesc
	ByteaSixAsc
	ByteaSixDesc
	ByteaSevenAsc
	ByteaSevenDesc
	ByteaEightAsc
	ByteaEightDesc
	TimeZeroAsc
	TimeZeroDesc
	TimeOneAsc
	TimeOneDesc
	TimeTwoAsc
	TimeTwoDesc
	TimeThreeAsc
	TimeThreeDesc
	TimeFiveAsc
	TimeFiveDesc
	TimeNineAsc
	TimeNineDesc
	TimeElevenAsc
	TimeElevenDesc
	TimeTwelveAsc
	TimeTwelveDesc
	TimeFifteenAsc
	TimeFifteenDesc
	TimeSixteenAsc
	TimeSixteenDesc
	JsonNullAsc
	JsonNullDesc
	JsonNnullAsc
	JsonNnullDesc
	TinyintNullAsc
	TinyintNullDesc
	TinyintNnullAsc
	TinyintNnullDesc
	Tinyint1NullAsc
	Tinyint1NullDesc
	Tinyint1NnullAsc
	Tinyint1NnullDesc
	Tinyint2NullAsc
	Tinyint2NullDesc
	Tinyint2NnullAsc
	Tinyint2NnullDesc
	SmallintNullAsc
	SmallintNullDesc
	SmallintNnullAsc
	SmallintNnullDesc
	MediumintNullAsc
	MediumintNullDesc
	MediumintNnullAsc
	MediumintNnullDesc
	BigintNullAsc
	BigintNullDesc
	BigintNnullAsc
	BigintNnullDesc
	FloatNullAsc
	FloatNullDesc
	FloatNnullAsc
	FloatNnullDesc
	DoubleNullAsc
	DoubleNullDesc
	DoubleNnullAsc
	DoubleNnullDesc
	DoubleprecNullAsc
	DoubleprecNullDesc
	DoubleprecNnullAsc
	DoubleprecNnullDesc
	RealNullAsc
	RealNullDesc
	RealNnullAsc
	RealNnullDesc
	BooleanNullAsc
	BooleanNullDesc
	BooleanNnullAsc
	BooleanNnullDesc
	DateNullAsc
	DateNullDesc
	DateNnullAsc
	DateNnullDesc
	DatetimeNullAsc
	DatetimeNullDesc
	DatetimeNnullAsc
	DatetimeNnullDesc
	TimestampNullAsc
	TimestampNullDesc
	TimestampNnullAsc
	TimestampNnullDesc
	BinaryNullAsc
	BinaryNullDesc
	BinaryNnullAsc
	BinaryNnullDesc
	VarbinaryNullAsc
	VarbinaryNullDesc
	VarbinaryNnullAsc
	VarbinaryNnullDesc
	TinyblobNullAsc
	TinyblobNullDesc
	TinyblobNnullAsc
	TinyblobNnullDesc
	BlobNullAsc
	BlobNullDesc
	BlobNnullAsc
	BlobNnullDesc
	MediumblobNullAsc
	MediumblobNullDesc
	MediumblobNnullAsc
	MediumblobNnullDesc
	LongblobNullAsc
	LongblobNullDesc
	LongblobNnullAsc
	LongblobNnullDesc
	VarcharNullAsc
	VarcharNullDesc
	VarcharNnullAsc
	VarcharNnullDesc
	CharNullAsc
	CharNullDesc
	CharNnullAsc
	CharNnullDesc
	TextNullAsc
	TextNullDesc
	TextNnullAsc
	TextNnullDesc
)

func (q *idxQuery[T]) OrderBy(args ...orderBy) coredb.ReadQuery[T] {
	q.orders = make([]string, len(args))
	for i, arg := range args {
		switch arg {
		case IdAsc:
			q.orders[i] = "`id` asc"
		case IdDesc:
			q.orders[i] = "`id` desc"
		case IdTwoAsc:
			q.orders[i] = "`id_two` asc"
		case IdTwoDesc:
			q.orders[i] = "`id_two` desc"
		case IdThreeAsc:
			q.orders[i] = "`id_three` asc"
		case IdThreeDesc:
			q.orders[i] = "`id_three` desc"
		case BoolZeroAsc:
			q.orders[i] = "`bool_zero` asc"
		case BoolZeroDesc:
			q.orders[i] = "`bool_zero` desc"
		case BoolOneAsc:
			q.orders[i] = "`bool_one` asc"
		case BoolOneDesc:
			q.orders[i] = "`bool_one` desc"
		case BoolTwoAsc:
			q.orders[i] = "`bool_two` asc"
		case BoolTwoDesc:
			q.orders[i] = "`bool_two` desc"
		case BoolThreeAsc:
			q.orders[i] = "`bool_three` asc"
		case BoolThreeDesc:
			q.orders[i] = "`bool_three` desc"
		case BoolFourAsc:
			q.orders[i] = "`bool_four` asc"
		case BoolFourDesc:
			q.orders[i] = "`bool_four` desc"
		case BoolFiveAsc:
			q.orders[i] = "`bool_five` asc"
		case BoolFiveDesc:
			q.orders[i] = "`bool_five` desc"
		case BoolSixAsc:
			q.orders[i] = "`bool_six` asc"
		case BoolSixDesc:
			q.orders[i] = "`bool_six` desc"
		case StringZeroAsc:
			q.orders[i] = "`string_zero` asc"
		case StringZeroDesc:
			q.orders[i] = "`string_zero` desc"
		case StringOneAsc:
			q.orders[i] = "`string_one` asc"
		case StringOneDesc:
			q.orders[i] = "`string_one` desc"
		case StringTwoAsc:
			q.orders[i] = "`string_two` asc"
		case StringTwoDesc:
			q.orders[i] = "`string_two` desc"
		case StringThreeAsc:
			q.orders[i] = "`string_three` asc"
		case StringThreeDesc:
			q.orders[i] = "`string_three` desc"
		case StringFourAsc:
			q.orders[i] = "`string_four` asc"
		case StringFourDesc:
			q.orders[i] = "`string_four` desc"
		case StringFiveAsc:
			q.orders[i] = "`string_five` asc"
		case StringFiveDesc:
			q.orders[i] = "`string_five` desc"
		case StringSixAsc:
			q.orders[i] = "`string_six` asc"
		case StringSixDesc:
			q.orders[i] = "`string_six` desc"
		case StringSevenAsc:
			q.orders[i] = "`string_seven` asc"
		case StringSevenDesc:
			q.orders[i] = "`string_seven` desc"
		case StringEightAsc:
			q.orders[i] = "`string_eight` asc"
		case StringEightDesc:
			q.orders[i] = "`string_eight` desc"
		case StringNineAsc:
			q.orders[i] = "`string_nine` asc"
		case StringNineDesc:
			q.orders[i] = "`string_nine` desc"
		case StringTenAsc:
			q.orders[i] = "`string_ten` asc"
		case StringTenDesc:
			q.orders[i] = "`string_ten` desc"
		case StringElevenAsc:
			q.orders[i] = "`string_eleven` asc"
		case StringElevenDesc:
			q.orders[i] = "`string_eleven` desc"
		case BigIntZeroAsc:
			q.orders[i] = "`big_int_zero` asc"
		case BigIntZeroDesc:
			q.orders[i] = "`big_int_zero` desc"
		case BigIntOneAsc:
			q.orders[i] = "`big_int_one` asc"
		case BigIntOneDesc:
			q.orders[i] = "`big_int_one` desc"
		case BigIntTwoAsc:
			q.orders[i] = "`big_int_two` asc"
		case BigIntTwoDesc:
			q.orders[i] = "`big_int_two` desc"
		case BigIntThreeAsc:
			q.orders[i] = "`big_int_three` asc"
		case BigIntThreeDesc:
			q.orders[i] = "`big_int_three` desc"
		case BigIntFourAsc:
			q.orders[i] = "`big_int_four` asc"
		case BigIntFourDesc:
			q.orders[i] = "`big_int_four` desc"
		case BigIntFiveAsc:
			q.orders[i] = "`big_int_five` asc"
		case BigIntFiveDesc:
			q.orders[i] = "`big_int_five` desc"
		case BigIntSixAsc:
			q.orders[i] = "`big_int_six` asc"
		case BigIntSixDesc:
			q.orders[i] = "`big_int_six` desc"
		case IntZeroAsc:
			q.orders[i] = "`int_zero` asc"
		case IntZeroDesc:
			q.orders[i] = "`int_zero` desc"
		case IntOneAsc:
			q.orders[i] = "`int_one` asc"
		case IntOneDesc:
			q.orders[i] = "`int_one` desc"
		case IntTwoAsc:
			q.orders[i] = "`int_two` asc"
		case IntTwoDesc:
			q.orders[i] = "`int_two` desc"
		case IntThreeAsc:
			q.orders[i] = "`int_three` asc"
		case IntThreeDesc:
			q.orders[i] = "`int_three` desc"
		case IntFourAsc:
			q.orders[i] = "`int_four` asc"
		case IntFourDesc:
			q.orders[i] = "`int_four` desc"
		case IntFiveAsc:
			q.orders[i] = "`int_five` asc"
		case IntFiveDesc:
			q.orders[i] = "`int_five` desc"
		case IntSixAsc:
			q.orders[i] = "`int_six` asc"
		case IntSixDesc:
			q.orders[i] = "`int_six` desc"
		case FloatZeroAsc:
			q.orders[i] = "`float_zero` asc"
		case FloatZeroDesc:
			q.orders[i] = "`float_zero` desc"
		case FloatOneAsc:
			q.orders[i] = "`float_one` asc"
		case FloatOneDesc:
			q.orders[i] = "`float_one` desc"
		case FloatTwoAsc:
			q.orders[i] = "`float_two` asc"
		case FloatTwoDesc:
			q.orders[i] = "`float_two` desc"
		case FloatThreeAsc:
			q.orders[i] = "`float_three` asc"
		case FloatThreeDesc:
			q.orders[i] = "`float_three` desc"
		case FloatFourAsc:
			q.orders[i] = "`float_four` asc"
		case FloatFourDesc:
			q.orders[i] = "`float_four` desc"
		case FloatFiveAsc:
			q.orders[i] = "`float_five` asc"
		case FloatFiveDesc:
			q.orders[i] = "`float_five` desc"
		case FloatSixAsc:
			q.orders[i] = "`float_six` asc"
		case FloatSixDesc:
			q.orders[i] = "`float_six` desc"
		case FloatSevenAsc:
			q.orders[i] = "`float_seven` asc"
		case FloatSevenDesc:
			q.orders[i] = "`float_seven` desc"
		case FloatEightAsc:
			q.orders[i] = "`float_eight` asc"
		case FloatEightDesc:
			q.orders[i] = "`float_eight` desc"
		case FloatNineAsc:
			q.orders[i] = "`float_nine` asc"
		case FloatNineDesc:
			q.orders[i] = "`float_nine` desc"
		case ByteaZeroAsc:
			q.orders[i] = "`bytea_zero` asc"
		case ByteaZeroDesc:
			q.orders[i] = "`bytea_zero` desc"
		case ByteaOneAsc:
			q.orders[i] = "`bytea_one` asc"
		case ByteaOneDesc:
			q.orders[i] = "`bytea_one` desc"
		case ByteaTwoAsc:
			q.orders[i] = "`bytea_two` asc"
		case ByteaTwoDesc:
			q.orders[i] = "`bytea_two` desc"
		case ByteaThreeAsc:
			q.orders[i] = "`bytea_three` asc"
		case ByteaThreeDesc:
			q.orders[i] = "`bytea_three` desc"
		case ByteaFourAsc:
			q.orders[i] = "`bytea_four` asc"
		case ByteaFourDesc:
			q.orders[i] = "`bytea_four` desc"
		case ByteaFiveAsc:
			q.orders[i] = "`bytea_five` asc"
		case ByteaFiveDesc:
			q.orders[i] = "`bytea_five` desc"
		case ByteaSixAsc:
			q.orders[i] = "`bytea_six` asc"
		case ByteaSixDesc:
			q.orders[i] = "`bytea_six` desc"
		case ByteaSevenAsc:
			q.orders[i] = "`bytea_seven` asc"
		case ByteaSevenDesc:
			q.orders[i] = "`bytea_seven` desc"
		case ByteaEightAsc:
			q.orders[i] = "`bytea_eight` asc"
		case ByteaEightDesc:
			q.orders[i] = "`bytea_eight` desc"
		case TimeZeroAsc:
			q.orders[i] = "`time_zero` asc"
		case TimeZeroDesc:
			q.orders[i] = "`time_zero` desc"
		case TimeOneAsc:
			q.orders[i] = "`time_one` asc"
		case TimeOneDesc:
			q.orders[i] = "`time_one` desc"
		case TimeTwoAsc:
			q.orders[i] = "`time_two` asc"
		case TimeTwoDesc:
			q.orders[i] = "`time_two` desc"
		case TimeThreeAsc:
			q.orders[i] = "`time_three` asc"
		case TimeThreeDesc:
			q.orders[i] = "`time_three` desc"
		case TimeFiveAsc:
			q.orders[i] = "`time_five` asc"
		case TimeFiveDesc:
			q.orders[i] = "`time_five` desc"
		case TimeNineAsc:
			q.orders[i] = "`time_nine` asc"
		case TimeNineDesc:
			q.orders[i] = "`time_nine` desc"
		case TimeElevenAsc:
			q.orders[i] = "`time_eleven` asc"
		case TimeElevenDesc:
			q.orders[i] = "`time_eleven` desc"
		case TimeTwelveAsc:
			q.orders[i] = "`time_twelve` asc"
		case TimeTwelveDesc:
			q.orders[i] = "`time_twelve` desc"
		case TimeFifteenAsc:
			q.orders[i] = "`time_fifteen` asc"
		case TimeFifteenDesc:
			q.orders[i] = "`time_fifteen` desc"
		case TimeSixteenAsc:
			q.orders[i] = "`time_sixteen` asc"
		case TimeSixteenDesc:
			q.orders[i] = "`time_sixteen` desc"
		case JsonNullAsc:
			q.orders[i] = "`json_null` asc"
		case JsonNullDesc:
			q.orders[i] = "`json_null` desc"
		case JsonNnullAsc:
			q.orders[i] = "`json_nnull` asc"
		case JsonNnullDesc:
			q.orders[i] = "`json_nnull` desc"
		case TinyintNullAsc:
			q.orders[i] = "`tinyint_null` asc"
		case TinyintNullDesc:
			q.orders[i] = "`tinyint_null` desc"
		case TinyintNnullAsc:
			q.orders[i] = "`tinyint_nnull` asc"
		case TinyintNnullDesc:
			q.orders[i] = "`tinyint_nnull` desc"
		case Tinyint1NullAsc:
			q.orders[i] = "`tinyint1_null` asc"
		case Tinyint1NullDesc:
			q.orders[i] = "`tinyint1_null` desc"
		case Tinyint1NnullAsc:
			q.orders[i] = "`tinyint1_nnull` asc"
		case Tinyint1NnullDesc:
			q.orders[i] = "`tinyint1_nnull` desc"
		case Tinyint2NullAsc:
			q.orders[i] = "`tinyint2_null` asc"
		case Tinyint2NullDesc:
			q.orders[i] = "`tinyint2_null` desc"
		case Tinyint2NnullAsc:
			q.orders[i] = "`tinyint2_nnull` asc"
		case Tinyint2NnullDesc:
			q.orders[i] = "`tinyint2_nnull` desc"
		case SmallintNullAsc:
			q.orders[i] = "`smallint_null` asc"
		case SmallintNullDesc:
			q.orders[i] = "`smallint_null` desc"
		case SmallintNnullAsc:
			q.orders[i] = "`smallint_nnull` asc"
		case SmallintNnullDesc:
			q.orders[i] = "`smallint_nnull` desc"
		case MediumintNullAsc:
			q.orders[i] = "`mediumint_null` asc"
		case MediumintNullDesc:
			q.orders[i] = "`mediumint_null` desc"
		case MediumintNnullAsc:
			q.orders[i] = "`mediumint_nnull` asc"
		case MediumintNnullDesc:
			q.orders[i] = "`mediumint_nnull` desc"
		case BigintNullAsc:
			q.orders[i] = "`bigint_null` asc"
		case BigintNullDesc:
			q.orders[i] = "`bigint_null` desc"
		case BigintNnullAsc:
			q.orders[i] = "`bigint_nnull` asc"
		case BigintNnullDesc:
			q.orders[i] = "`bigint_nnull` desc"
		case FloatNullAsc:
			q.orders[i] = "`float_null` asc"
		case FloatNullDesc:
			q.orders[i] = "`float_null` desc"
		case FloatNnullAsc:
			q.orders[i] = "`float_nnull` asc"
		case FloatNnullDesc:
			q.orders[i] = "`float_nnull` desc"
		case DoubleNullAsc:
			q.orders[i] = "`double_null` asc"
		case DoubleNullDesc:
			q.orders[i] = "`double_null` desc"
		case DoubleNnullAsc:
			q.orders[i] = "`double_nnull` asc"
		case DoubleNnullDesc:
			q.orders[i] = "`double_nnull` desc"
		case DoubleprecNullAsc:
			q.orders[i] = "`doubleprec_null` asc"
		case DoubleprecNullDesc:
			q.orders[i] = "`doubleprec_null` desc"
		case DoubleprecNnullAsc:
			q.orders[i] = "`doubleprec_nnull` asc"
		case DoubleprecNnullDesc:
			q.orders[i] = "`doubleprec_nnull` desc"
		case RealNullAsc:
			q.orders[i] = "`real_null` asc"
		case RealNullDesc:
			q.orders[i] = "`real_null` desc"
		case RealNnullAsc:
			q.orders[i] = "`real_nnull` asc"
		case RealNnullDesc:
			q.orders[i] = "`real_nnull` desc"
		case BooleanNullAsc:
			q.orders[i] = "`boolean_null` asc"
		case BooleanNullDesc:
			q.orders[i] = "`boolean_null` desc"
		case BooleanNnullAsc:
			q.orders[i] = "`boolean_nnull` asc"
		case BooleanNnullDesc:
			q.orders[i] = "`boolean_nnull` desc"
		case DateNullAsc:
			q.orders[i] = "`date_null` asc"
		case DateNullDesc:
			q.orders[i] = "`date_null` desc"
		case DateNnullAsc:
			q.orders[i] = "`date_nnull` asc"
		case DateNnullDesc:
			q.orders[i] = "`date_nnull` desc"
		case DatetimeNullAsc:
			q.orders[i] = "`datetime_null` asc"
		case DatetimeNullDesc:
			q.orders[i] = "`datetime_null` desc"
		case DatetimeNnullAsc:
			q.orders[i] = "`datetime_nnull` asc"
		case DatetimeNnullDesc:
			q.orders[i] = "`datetime_nnull` desc"
		case TimestampNullAsc:
			q.orders[i] = "`timestamp_null` asc"
		case TimestampNullDesc:
			q.orders[i] = "`timestamp_null` desc"
		case TimestampNnullAsc:
			q.orders[i] = "`timestamp_nnull` asc"
		case TimestampNnullDesc:
			q.orders[i] = "`timestamp_nnull` desc"
		case BinaryNullAsc:
			q.orders[i] = "`binary_null` asc"
		case BinaryNullDesc:
			q.orders[i] = "`binary_null` desc"
		case BinaryNnullAsc:
			q.orders[i] = "`binary_nnull` asc"
		case BinaryNnullDesc:
			q.orders[i] = "`binary_nnull` desc"
		case VarbinaryNullAsc:
			q.orders[i] = "`varbinary_null` asc"
		case VarbinaryNullDesc:
			q.orders[i] = "`varbinary_null` desc"
		case VarbinaryNnullAsc:
			q.orders[i] = "`varbinary_nnull` asc"
		case VarbinaryNnullDesc:
			q.orders[i] = "`varbinary_nnull` desc"
		case TinyblobNullAsc:
			q.orders[i] = "`tinyblob_null` asc"
		case TinyblobNullDesc:
			q.orders[i] = "`tinyblob_null` desc"
		case TinyblobNnullAsc:
			q.orders[i] = "`tinyblob_nnull` asc"
		case TinyblobNnullDesc:
			q.orders[i] = "`tinyblob_nnull` desc"
		case BlobNullAsc:
			q.orders[i] = "`blob_null` asc"
		case BlobNullDesc:
			q.orders[i] = "`blob_null` desc"
		case BlobNnullAsc:
			q.orders[i] = "`blob_nnull` asc"
		case BlobNnullDesc:
			q.orders[i] = "`blob_nnull` desc"
		case MediumblobNullAsc:
			q.orders[i] = "`mediumblob_null` asc"
		case MediumblobNullDesc:
			q.orders[i] = "`mediumblob_null` desc"
		case MediumblobNnullAsc:
			q.orders[i] = "`mediumblob_nnull` asc"
		case MediumblobNnullDesc:
			q.orders[i] = "`mediumblob_nnull` desc"
		case LongblobNullAsc:
			q.orders[i] = "`longblob_null` asc"
		case LongblobNullDesc:
			q.orders[i] = "`longblob_null` desc"
		case LongblobNnullAsc:
			q.orders[i] = "`longblob_nnull` asc"
		case LongblobNnullDesc:
			q.orders[i] = "`longblob_nnull` desc"
		case VarcharNullAsc:
			q.orders[i] = "`varchar_null` asc"
		case VarcharNullDesc:
			q.orders[i] = "`varchar_null` desc"
		case VarcharNnullAsc:
			q.orders[i] = "`varchar_nnull` asc"
		case VarcharNnullDesc:
			q.orders[i] = "`varchar_nnull` desc"
		case CharNullAsc:
			q.orders[i] = "`char_null` asc"
		case CharNullDesc:
			q.orders[i] = "`char_null` desc"
		case CharNnullAsc:
			q.orders[i] = "`char_nnull` asc"
		case CharNnullDesc:
			q.orders[i] = "`char_nnull` desc"
		case TextNullAsc:
			q.orders[i] = "`text_null` asc"
		case TextNullDesc:
			q.orders[i] = "`text_null` desc"
		case TextNnullAsc:
			q.orders[i] = "`text_nnull` asc"
		case TextNnullDesc:
			q.orders[i] = "`text_nnull` desc"
		}
	}
	return q
}

func (q *idxQuery[T]) All() []*T {
	result, _ := coredb.Find[T](DBName, TableName, q)
	return result
}

func (q *idxQuery[T]) Limit(offset, limit int) []*T {
	q.limitSql = fmt.Sprintf(" limit %d, %d", offset, limit)
	result, _ := coredb.Find[T](DBName, TableName, q)
	return result
}

type order[T any] interface {
	OrderBy(args ...orderBy) coredb.ReadQuery[T]
}

type orderReadQuery[T any] interface {
	order[T]
	coredb.ReadQuery[T]
}

type iQuery[T any] interface {
	orderReadQuery[T]
}

// Find methods

// Select returns rows from `type_monsters` table with index awared query
func Select() iQuery[TypeMonster] {
	return new(idxQuery[TypeMonster])
}

// SelectFields returns rows with selected fields from `type_monsters` table with index awared query
func SelectFields[T any]() iQuery[T] {
	return new(idxQuery[T])
}

func (q *idxQuery[T]) GetWhere() (whereSql string, params []any) {
	var orderSql string
	if len(q.orders) > 0 {
		orderSql = " order by " + strings.Join(q.orders, ",")
	}
	return q.whereSql + orderSql + q.limitSql, q.whereParams
}
